knp_gaufrette:
    adapters:
        gullkysten:
            aws_s3:
                service_id: 'aws.s3'
                bucket_name: '%aws.bucket.name%'
                options:
                    acl: public-read
                    create: true
    filesystems:
        gullkysten:
            adapter: gullkysten
            alias: gullkysten_filesystem

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
