security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER, ROLE_SONATA_ADMIN

        ROLE_ADMIN_DOCKEDSHIPS: ROLE_ADMIN

        ROLE_ADMIN_FELTDATA: ROLE_ADMIN

        ROLE_ADMIN_RIGGDATA: ROLE_ADMIN

        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        admin:
            pattern:  /admin(.*)
            form_login:
                login_path:  /admin/login
                use_forward:  false
                check_path:  /admin/login_check
                failure_path:  null
                default_target_path:   /admin/dashboard
            logout:
                path:  /admin/logout
                target: /admin/login
            anonymous:  true

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
        api_doc:
            pattern:    ^/api/doc
            security:   false
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true
        default:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            logout:
                path:  /logout
            anonymous:    true

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }